Renault_Alpine:
  - Benetton
  - Renault
  - Lotus F1 Team
  - Alpine
Aston_Martin:
  - Jordan
  - Midland
  - Spyker
  - Force India
  - Racing Point
  - Aston Martin
Mercedes:
  - Tyrrell
  - BAR
  - Honda
  - Brawn GP
  - Mercedes
RB:
  - Minardi
  - Toro Rosso
  - AlphaTauri
  - RB
Sauber_Stake:
  - Sauber
  - BMW Sauber
  - Alfa Romeo F1 Team
  - Stake F1 Team
