name: QA
on:
  push:
  pull_request:
jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install duckdb pandas
          pip install -e .
      - name: Run QA
        run: python tools/qa_v1.py
