name: QA

on:
  push:
    branches: [ main, release/*, feat/* ]
  pull_request:
    branches: [ main, release/* ]

permissions:
  contents: read

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install duckdb

      - name: Run QA
        run: |
          python tools/qa_v1.py

      - name: Archive exports (artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: exports
          path: |
            exports/*.csv
            exports/manifest_v1.json
